<?php include('include/soc_header.inc.php'); include('include/menu.inc.php'); ?>
<center><h1>Hunting Horn Music Sheet</h1>
<br>
<br>
<table id="tableItems">
<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set: <img src="images/HH/sw.png" style="text-align:left" width="40" height="30"><img src="images/HH/sd.b.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sr.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>

<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td><center>1 min 30 s</center></td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">No Stamina Loss [Lo]</td><td align="center">-</td><td align="center">1 min 30 s</td><td align="center">No Stamina Loss Extnd</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Wind Reduce</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Wind Cancel</td><td align="center">2 mins</td>

<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Attack Up [Lo]</td><td align="center">Attack +10%</td><td align="center">2 mins</td><td align="center">Attack +15%</td><td align="center">1 mins</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Health Inc [Lo]</td><td align="center">Health +20</td><td align="center">3 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sw.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sd.b.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sy.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">No Stamina Loss [Lo]</td><td align="center">-</td><td align="center">1 min 30 s</td><td align="center">No Stamina Loss Extnd</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Dragon Res Up [Lo]</td><td align="center">Dragon Resistance +10</td><td align="center">1 min</td><td align="center">Dragon Resistance +15</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">Thunder Res Up [Hi]</td><td align="center">Thunder Resistance +15</td><td align="center">1 min</center></td><td align="center">Thunder Resistance +20</td><td align="center">1 min</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Fire Res Up [Hi]</td><td align="center">Fire Resistance +15</td><td align="center">1 min</td><td align="center">Fire Resistance +20</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Water Res Up [Hi]</td><td align="center">Water Resistance +15</td><td align="center">1 min</td><td align="center">Water Resistance +20</td><td align="center">1 min</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Element Attack Up</td><td align="center">Adds 15% to element</td><td align="center">1 min 30 s</td><td align="center">Adds 20% to element</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center"><center>High-Frequency</center></td><td align="center">-</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sw.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sg.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sl.b.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>

<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td>Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">No Heat</td><td align="center">-</td><td align="center">4 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"></td><td align="center">HealthRec[Lo]&Antidote</td><td align="center">20 hp + Antidote effect</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">HealthRec[Mid]&Deodorant</td><td align="center">30 hp + Deodorant effect</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sw.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sy.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sr.png" style="vertical-align:left" width="40" height="30"></font></td></tr>

<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Dragon Res Up [Lo]</td><td align="center">Dragon Resistance +10</td><td align="center">1 min</td><td align="center">Dragon Resistance +15</td><td align="center">1 min</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Fire Res Up [Lo]</td><td align="center">Fire Resistance +10</td><td align="center">1 min</td><td align="center">Fire Resistance +15</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Attack Up [Lo]</td><td align="center">Attack +10%</td><td align="center">2 mins</td><td align="center">Attack +15%</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Defense Up [Lo]</td><td align="center">Defense +15%</td><td align="center">2 mins</td><td align="center">Defense +20%</td><td align="center">1 min 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center"><center>High-Frequency</center></td><td align="center">-</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sw.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sg.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sy.png" style="vertical-align:left" width="40" height="30"></font></td></tr>

<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"></td><td align="center">HealthRec[Lo]&Antidote</td><td align="center">20 hp + Antidote effect</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Recover Spd Up [Lo]</td><td align="center">-</td><td align="center">2 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Dragon Res Up [Lo]</td><td align="center">Dragon Resistance +10</td><td align="center">1 min</td><td align="center">Dragon Resistance +15</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Ice Res Up [Lo]</td><td align="center">Ice Resistance +10</td><td align="center">1 min</td><td align="center">Ice Resistance +15</td><td align="center">1 min</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center"><center>High-Frequency</center></td><td align="center">-</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sw.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sy.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sl.b.png" style="vertical-align:left" width="40" height="30"></font></td></tr>

<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Dragon Res Up [Lo]</td><td align="center">Dragon Resistance +10</td><td align="center">1 min</td><td align="center">Dragon Resistance +15</td><td align="center">1 min</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">Ice Res Up [Lo]</td><td align="center">Ice Resistance +10</td><td align="center">1 min</td><td align="center">Ice Resistance +15</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">No Cold & Snow Res</td><td align="center">-</td><td align="center">4 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">No Quakes</td><td align="center">-</td><td align="center">3 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">No Paralysis</td><td align="center">-</td><td align="center">3 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center"><center>High-Frequency</center></td><td align="center">-</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sw.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sg.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sr.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"></td><td align="center">HealthRec[Lo]&Antidote</td><td align="center">20 hp + Antidote effect</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Attack Up [Lo]</td><td align="center">Attack +10%</td><td align="center">2 mins</td><td align="center">Attack +15%</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Defense Up [Hi]</td><td align="center">Defense +20%</td><td align="center">1 min 30 s</td><td align="center">Defense +30%</td><td align="center">1 min</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sw.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sg.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sd.b.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"></td><td align="center">HealthRec[Lo]&Antidote</td><td align="center">20 hp + Antidote effect</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">No Stamina Loss [Lo]</td><td align="center">-</td><td align="center">1 min 30 s</td><td align="center">No Stamina Loss Extnd</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"></td><td align="center">Wind Cancel</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Wind All Cancel</td><td align="center">2 mins</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sw.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sl.b.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sd.b.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">No Stamina Loss [Lo]</td><td align="center">-</td><td align="center">1 min 30 s</td><td align="center">No Stamina Loss Extnd</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">Clairvoyance</td><td align="center">-</td><td align="center">30 s</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">Wind Cancel</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Wind All Cancel</td><td align="center">2 mins</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sw.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sl.b.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sr.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/w.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Hear Protect [Lo]</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Hear Protect [Hi]</td><td align="center">2 mins</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/w.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Attack Up [Lo]</td><td align="center">Attack +10%</td><td align="center">2 mins</td><td align="center">Attack +15%</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">Health Inc [Mid]</td><td align="center">Health +30</td><td align="center">3 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sp.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sd.b.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sy.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">No Stamina Loss [Hi]</td><td align="center">-</td><td align="center">2 mins 30 s</td><td align="center">No Stamina Loss Extnd</td><td align="center">2 mins 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/d.b.png" style="vertical-align:bottom">  <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Wind All Cancel</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Wind All Cancel</td><td align="center">3 mins</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Dragon Res Up [Hi]</td><td align="center">Dragon Resistance +15</td><td align="center">1 min</td><td align="center">Dragon Resistance +20</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">Thunder Res Up [Hi]</td><td align="center">Thunder Resistance +15</td><td align="center">1 min</td><td align="center">Thunder Resistance +20</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Water Res Up [Lo]</td><td align="center">Water Resistance +10</td><td align="center">1 min</td><td align="center">Water Resistance +15</td><td align="center">1 min</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">High-Frequency</td><td align="center">-</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sp.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sy.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sl.b.png" style="vertical-align:left" width="40" height="30"></font></td></tr>

<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Dragon Res Up [Hi]</td><td align="center">Dragon Resistance +15</td><td align="center">1 min</td><td align="center">Dragon Resistance +20</td><td align="center">1 min</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">Ice Res Up [Hi]</td><td align="center">Ice Resistance +15</td><td align="center">1 min</td><td align="center">Ice Resistance +20</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Thunder Res Up [Lo]</td><td align="center">Thunder Resistance +10</td><td align="center">1 min</td><td align="center">Thunder Resistance +15</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">No Cold & Snow Res</td><td align="center">-</td><td align="center">4 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">No Quakes</td><td align="center">-</td><td align="center">3 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">No Paralysis</td><td align="center">-</td><td align="center">3 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">High-Frequency</td><td align="center">-</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sp.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sd.b.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sr.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">No Stamina Loss [Hi]</td><td align="center">-</td><td align="center">2 mins 30 s</td><td align="center">No Stamina Loss Extnd</td><td align="center">2 mins 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Wind Reduce</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Wind Cancel</td><td align="center">2 mins</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Attack Up [Hi]</td><td align="center">Attack +15%</td><td align="center">1 min 30 s</td><td align="center">Attack +20%</td><td align="center">1 min</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Health Inc [Hi]</td><td align="center">Health +50</td><td align="center">3 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set: <img src="images/HH/sp.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sg.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sy.png" style="vertical-align:left" width="40" height="30"></font></td></tr>

<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"></td><td align="center">Health Rec [Lo]</td><td align="center">20 hp</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Health Rec [Mid]</td><td align="center">30 hp</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Recover Spd Up [Lo]</td><td align="center">-</td><td align="center">2 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Heavenly Protection</td><td align="center">50% chance of negating 30% damage</td><td align="center">2 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Dragon Res Up [Hi]</td><td align="center">Dragon Resistance +15</td><td align="center">1 min</td><td align="center">Dragon Resistance +20</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Ice Res Up [Hi]</td><td align="center">Ice Resistance +15</td><td align="center">1 min</td><td align="center">Ice Resistance +20</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">High-Frequency</td><td align="center">-</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sp.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sl.b.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sd.b.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">No Faint</td><td align="center">-</td><td align="center">3 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">No Stamina Loss [Hi]</td><td align="center">-</td><td align="center">2 mins 30 s</td><td align="center">No Stamina Loss Extnd</td><td align="center">2 mins 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">Clairvoyance</td><td align="center">-</td><td align="center">30 s</td><td align="center"></td><td align="center"></td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">Wind Cancel</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Wind All Cancel</td><td align="center">2 mins</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sp.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sy.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sr.png" style="vertical-align:left" width="40" height="30"></font></td></tr>

<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Dragon Res Up [Hi]</td><td align="center">Dragon Resistance +15</td><td align="center">1 min</td><td align="center">Dragon Resistance +20</td><td align="center">1 min</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Fire Res Up [Lo]</td><td align="center">Fire Resistance +10</td><td align="center">1 min</td><td align="center">Fire Resistance +15</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Attack Up [Hi]</td><td align="center">Attack +15%</td><td align="center">1 min 30 s</td><td align="center">Attack +20%</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">Defense Up [Lo]</td><td align="center">Defense +15%</td><td align="center">2 mins</td><td align="center">Defense +20%</td><td align="center">1 min 30 s</td</tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"> <img src="images/HH/y.png" style="vertical-align:bottom"></td><td align="center">High-Frequency</td><td align="center">-</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sp.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sg.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sd.b.png" style="vertical-align:left" width="40" height="30"></font></td></tr>

<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"></td><td align="center">Health Rec [Lo]</td><td align="center">20 hp</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">HealthRec[Mid]&Antidote</td><td align="center">30 hp + Antidote effect</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"></td><td align="center">No Stamina Loss [Hi]</td><td align="center">-</td><td align="center">2 mins 30 s</td><td align="center">No Stamina Loss Extnd</td><td align="center">2 mins 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/d.b.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"></td><td align="center">Wind Cancel</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Wind All Cancel</td><td align="center">2 mins</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sp.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sl.b.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sr.png" style="vertical-align:left" width="40" height="30"></font></td></tr>

<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Hear Protect [Lo]</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Hear Protect [Hi]</td><td align="center">2 mins</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Attack Up [Hi]</td><td align="center">Attack +15%</td><td align="center">1 min 30 s</td><td align="center">Attack +20%</td><td align="center">1 min</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">Health Inc [Mid]</td><td align="center">Health +30</td><td align="center">3 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Defense Up [Hi]</td><td align="center">Defense +20%</td><td align="center">1 min 30 s</td><td align="center">Defense +30%</td><td align="center">1 min</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>

<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set:</fonts> <img src="images/HH/sp.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sg.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sr.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"></td><td align="center">Health Rec [Lo]</td><td align="center">20 hp</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Recover Spd Up [Hi]</td><td align="center">-</td><td align="center">2 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Attack Up [Hi]</td><td align="center">Attack +15%</td><td align="center">1 min 30 s</td><td align="center">Attack +20%</td><td align="center">1 min</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/r.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/r.png" style="vertical-align:bottom"></td><td align="center">Defense Up [Hi]</td><td align="center">Defense +20%</td><td align="center">1 min 30 s</td><td align="center">Defense +30%</td><td align="center">1 min</td></tr></tbody>

<tr><td colspan="100"><br><br>&nbsp;</td></tr>
<tr>
<td colspan="6" align="left" width="50%"><font size="4pts" color="#D42F6A">Hunting Horn Colored Note Set: <img src="images/HH/sp.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sg.png" style="vertical-align:left" width="40" height="30"><img src="images/HH/sl.b.png" style="vertical-align:left" width="40" height="30"></font></td></tr>
<th><b>Note Combo</th><th bgcolor="#101010"><center><b>Effects</th><th bgcolor="#101010"><center><b>What it does</th><th bgcolor="#101010"><center><b>Duration</th><th bgcolor="#101010"><center><b>Extended Effects</th><th bgcolor="#101010"><center><b>Duration</th></tr>

<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"></td><td align="center">Movement Speed Up</td><td align="center">-</td><td align="center">3 mins</td><td align="center">Attacks Harder To Break</td><td align="center">1 min 30 s</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">Hear Protect [Hi]</td><td align="center">-</td><td align="center">3 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/l.b.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">No Heat</td><td align="center">-</td><td align="center">4 mins</td><td align="center">-</td><td align="center">-</td></tr></tbody>

<tbody class="odd"><tr><td align="center"><img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"></td><td align="center">Health Rec [Lo]</td><td align="center">20 hp</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>
<tbody class="odd"><tr><td align="center"><img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/g.png" style="vertical-align:bottom"> <img src="images/HH/p.png" style="vertical-align:bottom"> <img src="images/HH/l.b.png" style="vertical-align:bottom"></td><td align="center">Health Rec [High]</td><td align="center">40 hp</td><td align="center">-</td><td align="center">-</td><td align="center">-</td></tr></tbody>
</table>

</center>


<?php include('include/soc_footer.inc.php'); ?>
